import { type NextPage } from "next";
import React, { useState, useEffect } from "react";
import { SignIn, SignInButton, useUser } from "@clerk/nextjs";
import { SignOutButton } from "@clerk/clerk-react";
import Head from "next/head";
import Link from "next/link";

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

import { api } from "~/utils/api";
import { RouterOutputs } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  //   if (isLoading) return <div>Loading...</div>;
  //   if (!data) return <div>....Something went wrong.</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center bg-zinc-200 align-middle dark:bg-zinc-900">
        <div className="flex w-full items-center justify-center border-x border-zinc-200  dark:text-white md:max-w-2xl">
          <div className="border-b border-zinc-500 p-4">
            {!user.isSignedIn && (
              <div className=" flex justify-center text-center">
                <SignInButton />
              </div>
            )}

            {user.isSignedIn && (
              <div className="">
                <SignOutButton />
              </div>
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
